CREATE TABLE SUBREDDIT (
    SUBREDDIT_ID UUID DEFAULT RANDOM_UUID(),
    NAME VARCHAR(255),
    IMAGE VARCHAR(255),
    PRIMARY KEY (SUBREDDIT_ID)
);

CREATE TABLE POST (
    POST_ID UUID DEFAULT RANDOM_UUID(),
    TITLE VARCHAR(255),
    POST_COMMENT TEXT,
    AUTHOR VARCHAR(255),
    SUBREDDIT_ID UUID,
    SCORE INT,
    IMG VARCHAR(255),
    PRIMARY KEY (POST_ID),
    FOREIGN KEY (SUBREDDIT_ID) REFERENCES SUBREDDIT(SUBREDDIT_ID)
);

CREATE TABLE COMMENT (
    COMMENT_ID UUID DEFAULT RANDOM_UUID(),
    COMMENT_AUTHOR VARCHAR(255),
    COMMENT_TEXT TEXT,
    COMMENT_SCORE INT,
    POST_ID UUID,
    PRIMARY KEY (COMMENT_ID),
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID)
);

-- A tabela de relacionamento entre POSTS e COMMENTS será criada automaticamente quando você inserir dados.
